server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-binding-errors: never

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  web:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: ERROR
    com.zaxxer.hikari: INFO

app:
  frontend:
    url: ${ALLOWED_ORIGINS}
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000
    access-expiration-minutes: 15
    refresh-expiration-days: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
